In [1]:
import pandas as pd

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df = pd.read_csv("Spam_SMS.csv")

In [4]:
df

     Class                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5569  spam  This is the 2nd time we have tried 2 contact u...
5570   ham               Will ü b going to esplanade fr home?
5571   ham  Pity, * was in mood for that. So...any other s...
5572   ham  The guy did some bitching but I acted like i'd...
5573   ham                         Rofl. Its true to its name

[5574 rows x 2 columns]

In [5]:
df.isna().sum()

Class      0
Message    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(415)

In [7]:
df = df.drop_duplicates()

In [8]:
df.head()

  Class                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["Class"] = df["Class"].str.replace("ham", "NonSpam")

C:\Users\USER\AppData\Local\Temp\ipykernel_16684\2422964182.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Class"] = df["Class"].str.replace("ham", "NonSpam")

In [12]:
df["Class"].value_counts(dropna=False)

Class
NonSpam    4518
spam        641
Name: count, dtype: int64

In [13]:
x_train,x_test, y_train,y_test = train_test_split(
    df['Message'],df['Class'],test_size = 0.2,random_state = 42
)

In [14]:
Vectorizer = CountVectorizer()

In [15]:
Vectorizer

CountVectorizer()

In [16]:
x_train_vec = Vectorizer.fit_transform(x_train)
x_test_vec = Vectorizer.transform(x_test)

In [17]:
model = MultinomialNB()

In [18]:
model

MultinomialNB()

In [19]:
model.fit(x_train_vec,y_train)

MultinomialNB()

In [20]:
y_pred = model.predict(x_test_vec)

In [21]:
y_pred

array(['NonSpam', 'NonSpam', 'NonSpam', ..., 'NonSpam', 'NonSpam',
       'NonSpam'], shape=(1032,), dtype='<U7')

In [22]:
print("Accuracy =", accuracy_score(y_test,y_pred)*100)

Accuracy = 98.15891472868216

In [23]:
results = pd.DataFrame({
    "Message" : x_test,
    "Actual" : y_test,
    "Predicted" : y_pred
})
results

                                                Message   Actual Predicted
4994  "HEY KATE, HOPE UR OK... WILL GIVE U A BUZ WED...  NonSpam   NonSpam
3745  Nobody names their penis a girls name this sto...  NonSpam   NonSpam
667   Carlos'll be here in a minute if you still nee...  NonSpam   NonSpam
1111                            Ok ill tell the company  NonSpam   NonSpam
2633                     I WILL CAL YOU SIR. In meeting  NonSpam   NonSpam
...                                                 ...      ...       ...
1065  That's fine, I'll bitch at you about it later ...  NonSpam   NonSpam
1791  Am not working but am up to eyes in philosophy...  NonSpam   NonSpam
2441  Great. I'm in church now, will holla when i ge...  NonSpam   NonSpam
3924  Okay lor... Will they still let us go a not ah...  NonSpam   NonSpam
3041  One day a crab was running on the sea shore..T...  NonSpam   NonSpam

[1032 rows x 3 columns]

In [24]:
df.head(20)

      Class                                            Message
0   NonSpam  Go until jurong point, crazy.. Available only ...
1   NonSpam                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   NonSpam  U dun say so early hor... U c already then say...
4   NonSpam  Nah I don't think he goes to usf, he lives aro...
5      spam  FreeMsg Hey there darling it's been 3 week's n...
6   NonSpam  Even my brother is not like to speak with me. ...
7   NonSpam  As per your request 'Melle Melle (Oru Minnamin...
8      spam  WINNER!! As a valued network customer you have...
9      spam  Had your mobile 11 months or more? U R entitle...
10  NonSpam  I'm gonna be home soon and i don't want to tal...
11     spam  SIX chances to win CASH! From 100 to 20,000 po...
12     spam  URGENT! You have won a 1 week FREE membership ...
13  NonSpam  I've been searching for the right words to tha...
14  NonSpam                I HAVE A DATE ON SUNDAY WITH WILL!!
15     spam  XXXMobileMovieClub: To use your credit, click ...
16  NonSpam                         Oh k...i'm watching here:)
17  NonSpam  Eh u remember how 2 spell his name... Yes i di...
18  NonSpam  Fine if that’s the way u feel. That’s the way ...
19     spam  England v Macedonia - dont miss the goals/team...

In [29]:
print("Classification Report:\n")
print(classification_report(y_test, y_pred))

Classification Report:

              precision    recall  f1-score   support

     NonSpam       0.99      0.99      0.99       911
        spam       0.93      0.91      0.92       121

    accuracy                           0.98      1032
   macro avg       0.96      0.95      0.96      1032
weighted avg       0.98      0.98      0.98      1032